spring.application.name=DyanmicQRPlatform
spring.data.mongodb.uri=mongodb+srv://root-qr:root@cluster0.qberb6z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=qrplatform

server.port=5000

# JWT Secret
jwt.secret=123456

# Enable CORS if needed
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
